# Generated by Django 4.2.30 on 2026-08-11 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de actividad',
                'verbose_name_plural': 'Tipos de actividad',
            },
        ),
        migrations.CreateModel(
            name='ArchiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Clase de archivo',
                'verbose_name_plural': 'Clases de archivo',
            },
        ),
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Clase de cliente',
                'verbose_name_plural': 'Clases de cliente',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('date_of_constitution', models.DateField(verbose_name='Fecha de constitución')),
                ('web_site', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('word_clave', models.CharField(blank=True, max_length=100, null=True, verbose_name='Palabras clave')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='files.activitytype', verbose_name='Tipo de actividad')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='files.classname', verbose_name='Clase de cliente')),
            ],
            options={
                'verbose_name': '1 - Cliente',
                'verbose_name_plural': '1 - Clientes',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='files.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': '2 - Persona',
                'verbose_name_plural': '2 - Personas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFileArchive',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del archivo')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Nombre original')),
                ('blob_path', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Ruta en Azure Blob')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño (Bytes)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('upload_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('ERROR', 'Error')], default='PENDING', editable=False, max_length=20, verbose_name='Estado de procesamiento')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True, verbose_name='ID de tarea Celery')),
                ('error_message', models.TextField(blank=True, editable=False, null=True, verbose_name='Mensaje de error')),
                ('error_traceback', models.TextField(blank=True, editable=False, null=True, verbose_name='Traceback')),
                ('processed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Procesado en')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='Fecha de apertura')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('uploaded_at', models.DateTimeField(blank=True, editable=False, verbose_name='Subido en')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado en')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('archive_class', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='files.archiveclass', verbose_name='Clase de archivo')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='files.customer', verbose_name='Cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'historical 3 - Archivo',
                'verbose_name_plural': 'historical 3 - Archivos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FileArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del archivo')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Nombre original')),
                ('blob_path', models.CharField(blank=True, max_length=512, unique=True, verbose_name='Ruta en Azure Blob')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño (Bytes)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('upload_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('ERROR', 'Error')], default='PENDING', editable=False, max_length=20, verbose_name='Estado de procesamiento')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True, verbose_name='ID de tarea Celery')),
                ('error_message', models.TextField(blank=True, editable=False, null=True, verbose_name='Mensaje de error')),
                ('error_traceback', models.TextField(blank=True, editable=False, null=True, verbose_name='Traceback')),
                ('processed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Procesado en')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='Fecha de apertura')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('archive_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_archives', to='files.archiveclass', verbose_name='Clase de archivo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_archives', to='files.customer', verbose_name='Cliente')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_archives', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': '3 - Archivo',
                'verbose_name_plural': '3 - Archivos',
            },
        ),
    ]
