# Generated by Django 4.2.30 on 2026-08-15 00:17

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filearchive',
            name='blob_path',
        ),
        migrations.RemoveField(
            model_name='historicalfilearchive',
            name='blob_path',
        ),
        migrations.AddField(
            model_name='filearchive',
            name='file',
            field=models.FileField(blank=True, max_length=255, upload_to=files.models.file_archive_upload_to, verbose_name='Archivo'),
        ),
        migrations.AddField(
            model_name='historicalfilearchive',
            name='file',
            field=models.TextField(blank=True, max_length=255, verbose_name='Archivo'),
        ),
    ]
